version: "2"
services:
  miq-app:
    image: docker.io/fbladilo/manageiq-pods:app-latest
    privileged: true
    working_dir: /
    environment:
    - "APPLICATION_INIT_DELAY={{ '{{ application_init_delay }}' }}"
    - "DATABASE_REGION={{ '{{ database_region }}' }}"
    - "DATABASE_SERVICE_NAME={{ '{{ database_service_name }}' }}"
    - "MEMCACHED_SERVICE_NAME={{ '{{ memcached_service_name }}' }}"
    - "MIQ_MEMCACHED_PORT={{ '{{ miq_memcached_port }}' }}"
    - "MIQ_MEMCACHED_PORT_11211_TCP={{ '{{ miq_memcached_port_11211_tcp }}' }}"
    - "MIQ_MEMCACHED_PORT_11211_TCP_ADDR={{ '{{ miq_memcached_port_11211_tcp_addr }}' }}"
    - "MIQ_MEMCACHED_SERVICE_HOST={{ '{{ miq_memcached_service_host }}' }}"
    - "MIQ_POSTGRESQL_PORT={{ '{{ miq_postgresql_port }}' }}"
    - "MIQ_POSTGRESQL_PORT_5432_TCP={{ '{{ miq_postgresql_port_5432_tcp }}' }}"
    - "MIQ_POSTGRESQL_PORT_5432_TCP_ADDR={{ '{{ miq_postgresql_5432_tcp_port }}' }}"
    - "MIQ_POSTGRESQL_SERVICE_HOST={{ '{{ miq_postgresql_service_host }}' }}"
    - "POSTGRESQL_DATABASE={{ '{{ postgresql_database }}' }}"
    - "POSTGRESQL_PASSWORD={{ '{{ postgresql_password }}' }}"
    - "POSTGRESQL_USER={{ '{{ postgresql_user }}' }}"
    expose:
    - 80
    - 443
    volumes:
    - miq-app:/persistent:rw
    options:
      openshift:
        persistent_volume_claims:
        - volume_name: miq-app
          claim_name: miq-app
          access_modes:
          - ReadWriteOnce
  miq-memcached:
    image: docker.io/fbladilo/manageiq-pods:memcached-latest
    working_dir: /
    environment:
    - "MEMCACHED_MAX_CONNECTIONS={{ '{{ memcached_max_connections }}' }}"
    - "MEMCACHED_MAX_MEMORY={{ '{{ memcached_max_memory }}' }}"
    - "MEMCACHED_SLAB_PAGE_SIZE={{ '{{ memcached_slab_page_size }}' }}"
    expose:
    - 11211
  miq-postgresql:
    image: docker.io/fbladilo/manageiq-pods:postgresql-latest
    working_dir: /
    environment:
    - "POSTGRESQL_DATABASE={{ '{{ postgresql_database }}' }}"
    - "POSTGRESQL_PASSWORD={{ '{{ postgresql_password }}' }}"
    - "POSTGRESQL_USER={{ '{{ postgresql_user }}' }}"
    expose:
    - 5432
    volumes:
    - miq-postgresql:/var/lib/pgsql/data:rw
    options:
      openshift:
        persistent_volume_claims:
        - volume_name: miq-postgresql
          claim_name: miq-postgresql
          access_modes:
          - ReadWriteOnce
volumes:
  miq-app: {}
  miq-postgresql: {}
