# TODO: Need to regenerate this file using ansibleapp tooling
# and add spec to be encoded and stamped as label
FROM ansibleapp/ansibleapp-base

MAINTAINER Dylan Murray <dymurray@redhat.com>

ADD ansible /opt/ansible
ADD ansibleapp/actions /opt/ansibleapp/actions
