---
aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"
backup_retention: "{{ lookup('env','BACKUP_RETENTION') | default(0, true) }}"
db_engine: "{{ lookup('env','DB_ENGINE') | default('postgres', true) }}"
db_name: "{{ lookup('env','DB_NAME') | default('testdb', true) }}"
db_password: "{{ lookup('env','DB_PASSWORD') | default('dbpasswd', true) }}"
db_size: "{{ lookup('env','DB_SIZE') | default(10, true) }}"
db_username: "{{ lookup('env','DB_USERNAME') | default('dbuser', true) }}"
engine_version: "{{ lookup('env','ENGINE_VERSION') | default(9.6.1, true) }}"
instance_type: "{{ lookup('env','INSTANCE_TYPE') | default('db.m3.medium', true) }}"
namespace: "{{ lookup('env','NAMESPACE') | default('rds-apb', true) }}"
openshift_target: "{{ lookup('env','OPENSHIFT_TARGET') }}"
openshift_user: "{{ lookup('env','OPENSHIFT_USER') }}"
openshift_pass: "{{ lookup('env','OPENSHIFT_PASS') }}"
port: "{{ lookup('env','PORT') | default(5432, true) }}"
region: "{{ lookup('env','REGION') }}"
subnet: "{{ lookup('env','SUBNET') }}"
vpc_security_groups: "{{ lookup('env','VPC_SECURITY_GROUPS') }}"
