
- oso_service:
    service_name: mongodb
    project_name: "{{ namespace }}"
    labels:
      app: mongodb-ansibleapp
      service: mongodb
    ports:
    - name: port-27017
      port: 27017
      targetPort: 27017
    selector:
      app: mongodb-ansibleapp
      service: mongodb
  register: output

- debug: var=output
  when: playbook_debug

- oso_deployment:
    project_name: "{{ namespace }}"
    labels:
      app: mongodb-ansibleapp
      service: mongodb
    deployment_name: mongodb
    containers:
    - securityContext: {}
      name: mongodb
      env:
        DATABASE_PASS: '{{ database_pass }}'
        DATABASE_USER: '{{ database_user }}'
      workingDir: /
      volumeMounts:
      - mountPath: /data/db
        name: mongodb
        readOnly: false
      image: jmontleon/mongodb:centos7
      ports:
      - 27017
    replace: true
    volumes:
    - name: mongodb
      persistentVolumeClaim:
        claimName: mongodb
  register: output

- debug: var=output
  when: playbook_debug

- oso_pvc:
    state: present
    project_name: "{{ namespace }}"
    name: mongodb
    access_modes:
    - ReadWriteOnce
  register: output

- debug: var=output
  when: playbook_debug
