---
# defaults for galera-ansibleapp-openshift

playbook_debug: no
create_pvs: "{{ lookup('env','CREATE_PVS') | default('pulp-ansibleapp', false) }}"
namespace: "{{ lookup('env','NAMESPACE') | default('pulp-ansibleapp', true) }}"
pulp_password: "{{ lookup('env','PULP_PASSWORD') | default('admin', true) }}"
pv_base_path: "{{ lookup('env','PV_BASE_PATH') | default('/opt/k8s', false) }}"
openshift_target: "{{ lookup('env','OPENSHIFT_TARGET') }}"
openshift_user: "{{ lookup('env','OPENSHIFT_USER') }}"
openshift_pass: "{{ lookup('env','OPENSHIFT_PASS') }}"
