- hosts: all
  vars:
    ansibleapp_dir: /opt/ansibleapp
  tasks:
    - name: Bind
      shell: './bind'
      environment:
        BIND_PARAMS: "{{bind_params | to_json}}"
        PROVISION_PARAMS: "{{provision_params | to_json}}"
      args:
        chdir: "{{ansibleapp_dir}}"
      register: bind_out
    - debug: msg={{bind_out.stdout}}
