- hosts: all
  vars:
    ansibleapp_dir: /opt/ansibleapp
    rendered_resource: /tmp/provision-svc-endpoint.yaml
    _project_name: "{{project_name | default('external-mlab', true)}}"
  tasks:
    - name: Create new project
      shell: "oc new-project {{_project_name}}"
    - name: Activate project
      shell: "oc project {{_project_name}}"
    - name: Render resource
      template:
        src: "{{ansibleapp_dir}}/provision-svc-endpoint.yaml.j2"
        dest: "{{rendered_resource}}"
        owner: ansibleapp
        mode: '0666'
    - name: Create resource
      shell: "oc create -f {{rendered_resource}} --namespace={{_project_name}}"
