---

- name: install epel
  yum: name=epel-release state=latest

- name: Install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - php
    - php-mysql
    - php-gd
    - psmisc
    - tar
    - ansible

- name: untar
  unarchive:
    remote_src: yes
    src: http://wordpress.org/latest.tar.gz
    dest: /var/www/html
    group: apache
    owner: apache
    mode: u=rwx,g=rwx,o=rwx

- name: Copy the sample file
  command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php

- name: Change DocumentRoot
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: "(.)+DocumentRoot /var/www/html"
    line: "DocumentRoot /var/www/html/wordpress"

- name: Create setup directory
  file:
    path: /setup
    state: directory
    owner: apache
    group: root
    mode: 0775

- name: Copy initialization script
  copy:
    src: initialize.yml
    dest: /setup/initialize.yml
    owner: apache
    group: root
    mode: 0775

- name: Copy entrypoint
  copy:
    src: entrypoint.sh
    dest: /usr/bin/entrypoint.sh
    owner: apache
    group: root
    mode: 0775
