version: "2"

services:
  wordpress:
    image: centos:7
    expose:
      - 80
    links:
      - mariadb
    depends_on:
      - mariadb
    entrypoint:
      - /usr/bin/entrypoint.sh
    user: apache
    command: ['/usr/sbin/apachectl', '-D', 'FOREGROUND']
    environment:
      - "DATABASE_USER={{ '{{ database_user }}' }}"
      - "DATABASE_PASSWORD={{ '{{ database_password }}' }}"
      - "DATABASE_NAME={{ '{{ database_name }}' }}"
      - "DATABASE_HOST={{ '{{ database_host }}' }}"
      - "DATABASE_PORT=3306"

  mariadb:
    image: centos:7
    expose:
      - 3306
    volumes:
      - mariadb-storage:/var/lib/mysql:rw
      - mariadb-logs:/var/log/mysql:rw
    environment:
      - "MARIADB_DATABASE={{ '{{ database_name }}' }}"
      - "MARIADB_USERNAME={{ '{{ database_user }}' }}"
      - "MARIADB_PASSWORD={{ '{{ database_password }}' }}"
      - "MARIADB_ROOT_PASSWORD={{ '{{ root_password }}' }}"
    entrypoint: [/usr/bin/entrypoint.sh]
    command: ['/usr/bin/dumb-init', 'mysqld']
    user: mysql
    options:
      openshift:
        persistent_volume_claims:
        - volume_name: mariadb-storage
          claim_name: mariadb-storage
          access_modes:
            - ReadWriteOnce
        - volume_name: mariadb-logs
          claim_name: mariadb-logs
          access_modes:
            - ReadWriteOnce

volumes:
  mariadb-storage: {}
  mariadb-logs: {}


registries: {}
