# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/
#
#---
- hosts: mariadb-1
  vars:
    mariadb_root_password: sesame
    wsrep_cluster_addresses: mariadb-1,mariadb-2,mariadb-3
    wsrep_node_name: mariadb-1
  gather_facts: false
  roles:
   - jmontleon.galera-container
- hosts: mariadb-2
  vars:
    mariadb_root_password: sesame
    wsrep_cluster_addresses: mariadb-1,mariadb-2,mariadb-3
    wsrep_node_name: mariadb-2
  gather_facts: false
  roles:
   - jmontleon.galera-container
- hosts: mariadb-3
  vars:
    mariadb_root_password: sesame
    wsrep_cluster_addresses: mariadb-1,mariadb-2,mariadb-3
    wsrep_node_name: mariadb-3
  gather_facts: false
  roles:
   - jmontleon.galera-container
