
- oso_service:
    service_name: mariadb
    project_name: wordpress-ansibleapp
    labels:
      app: wordpress-ansibleapp
      service: mariadb
    ports:
    - name: port-3306
      port: 3306
      targetPort: 3306
    selector:
      app: wordpress-ansibleapp
      service: mariadb
  register: output

- debug: var=output
  when: playbook_debug

- oso_deployment:
    project_name: wordpress-ansibleapp
    labels:
      app: wordpress-ansibleapp
      service: mariadb
    deployment_name: mariadb
    containers:
    - securityContext: {}
      name: mariadb
      image: wordpress-ansibleapp-mariadb:20170217201726
      env:
        MARIADB_DATABASE: '{{ database_name }}'
        MARIADB_PASSWORD: '{{ database_password }}'
        MARIADB_ROOT_PASSWORD: '{{ root_password }}'
        MARIADB_USERNAME: '{{ database_user }}'
      args:
      - /usr/bin/dumb-init
      - mysqld
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: mariadb-storage
        readOnly: false
      - mountPath: /var/log/mysql
        name: mariadb-logs
        readOnly: false
      command:
      - /usr/bin/entrypoint.sh
      ports:
      - 3306
    replace: true
    volumes:
    - name: mariadb-storage
      persistentVolumeClaim:
        claimName: mariadb-storage
    - name: mariadb-logs
      persistentVolumeClaim:
        claimName: mariadb-logs
  register: output

- debug: var=output
  when: playbook_debug

- oso_deployment:
    project_name: wordpress-ansibleapp
    labels:
      app: wordpress-ansibleapp
      service: wordpress
    deployment_name: wordpress
    containers:
    - securityContext: {}
      name: wordpress
      env:
        DATABASE_HOST: '{{ database_host }}'
        DATABASE_NAME: '{{ database_name }}'
        DATABASE_PASSWORD: '{{ database_password }}'
        DATABASE_PORT: '3306'
        DATABASE_USER: '{{ database_user }}'
      command:
      - /usr/bin/entrypoint.sh
      args:
      - /usr/sbin/apachectl
      - -D
      - FOREGROUND
      image: wordpress-ansibleapp-wordpress:20170217201726
    replace: true
  register: output

- debug: var=output
  when: playbook_debug

- oso_pvc:
    state: present
    project_name: wordpress-ansibleapp
    name: mariadb-storage
    access_modes:
    - ReadWriteOnce
  register: output

- debug: var=output
  when: playbook_debug

- oso_pvc:
    state: present
    project_name: wordpress-ansibleapp
    name: mariadb-logs
    access_modes:
    - ReadWriteOnce
  register: output

- debug: var=output
  when: playbook_debug
